# Generated by Django 4.2.16 on 2024-09-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0069_merge_20240514_1008'),
        ('order', '0194_merge_20240805_0820'),
        ('attribute', '0046_auto_20240611_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=32, unique=True)),
                ('extension', models.CharField(max_length=16)),
                ('name', models.CharField(db_index=True, max_length=127)),
                ('base_url', models.CharField(blank=True, max_length=127)),
                ('page_count', models.IntegerField(null=True)),
                ('colored_pages', models.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('text_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='attribute.attribute')),
            ],
            options={
                'ordering': ('pk', 'hash'),
            },
        ),
        migrations.CreateModel(
            name='UploadedFileLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=32, null=True)),
                ('name', models.CharField(db_index=True, max_length=127, null=True)),
                ('choosed_colored_pages', models.JSONField(null=True)),
                ('duplex', models.BooleanField(blank=True, default=False, null=True)),
                ('copies', models.IntegerField(default=1)),
                ('role', models.CharField(default='pdf', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('pages_per_sheet', models.IntegerField(default=1, null=True)),
                ('checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_lines', to='checkout.checkout')),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_lines', to='file_print.uploadedfile', to_field='hash')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_lines', to='file_print.uploadedfile', to_field='hash')),
                ('order', models.ForeignKey(blank=True, db_column='order_token', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_lines', to='order.order')),
            ],
            options={
                'ordering': ('hash', 'pk'),
            },
        ),
    ]
