# Generated by Django 3.2.12 on 2022-02-24 09:13
# NOTE: Fixes for migration from the old guug database have been added here, 
# they should be removed after a successful migration.

import uuid

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("order", "0130_save_order_token_in_relation_models"),
        ("account", "0063_save_customerevent_order_token"),
        ("discount", "0036_save_discocunt_order_token"),
        ("invoice", "0007_save_invoice_order_token"),
        ("payment", "0032_save_payment_order_token"),
    ]

    operations = [
         # Step 1: Create a temporary table for file_print_uploadedfileline
        migrations.RunSQL(
            """
                CREATE TABLE file_print_uploadedfileline_temp AS
                SELECT * FROM file_print_uploadedfileline;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
         # Step 2: Drop the original file_print_uploadedfileline table
        migrations.RunSQL(
            """
                DROP TABLE file_print_uploadedfileline;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
                ALTER TABLE order_order
                DROP CONSTRAINT order_order_pkey;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="order",
            name="token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        # Step 3: Recreate the file_print_uploadedfileline table with updated foreign key
        migrations.RunSQL(
            """
                CREATE TABLE file_print_uploadedfileline (
                    id SERIAL PRIMARY KEY,
                    choosed_colored_pages jsonb,
                    duplex boolean,
                    file_id character varying(32),
                    role character varying(16) NOT NULL,
                    created timestamp with time zone,
                    hash character varying(32),
                    copies integer NOT NULL,
                    name character varying(127),
                    checkout_id uuid,
                    order_token uuid,
                    pages_per_sheet integer,
                    cover_id character varying(32),
                    FOREIGN KEY (checkout_id) REFERENCES public.checkout_checkout (token) ON UPDATE NO ACTION ON DELETE NO ACTION,
                    FOREIGN KEY (cover_id) REFERENCES public.file_print_uploadedfile (hash) ON UPDATE NO ACTION ON DELETE NO ACTION,
                    FOREIGN KEY (file_id) REFERENCES public.file_print_uploadedfile (hash) ON UPDATE NO ACTION ON DELETE NO ACTION,
                    FOREIGN KEY (order_token) REFERENCES public.order_order (token) ON UPDATE NO ACTION ON DELETE NO ACTION
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
                INSERT INTO file_print_uploadedfileline (choosed_colored_pages, duplex, file_id, role, created, hash, copies, name, checkout_id, order_token, pages_per_sheet, cover_id)
                SELECT choosed_colored_pages, duplex, file_id, role, created, hash, copies, name, checkout_id,
                       (SELECT token FROM order_order WHERE id = order_id) AS order_token,
                       pages_per_sheet, cover_id
                FROM file_print_uploadedfileline_temp;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 4: Drop the temporary table
        migrations.RunSQL(
            """
                DROP TABLE file_print_uploadedfileline_temp;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name="order",
            name="id",
        ),
    ]
